// Code generated by entc, DO NOT EDIT.

package language

const (
	// Label holds the string label denoting the language type in the database.
	Label = "language"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTalk holds the string denoting the talk field in the database.
	FieldTalk = "talk"
	// FieldWrite holds the string denoting the write field in the database.
	FieldWrite = "write"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldListen holds the string denoting the listen field in the database.
	FieldListen = "listen"
	// Table holds the table name of the language in the database.
	Table = "languages"
)

// Columns holds all SQL columns for language fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTalk,
	FieldWrite,
	FieldRead,
	FieldListen,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
