// Code generated by entc, DO NOT EDIT.

package hook

import (
	"Kynesia/ent"
	"context"
	"fmt"
)

// The AchievementFunc type is an adapter to allow the use of ordinary
// function as Achievement mutator.
type AchievementFunc func(context.Context, *ent.AchievementMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AchievementFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.AchievementMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AchievementMutation", m)
	}
	return f(ctx, mv)
}

// The BiodataFunc type is an adapter to allow the use of ordinary
// function as Biodata mutator.
type BiodataFunc func(context.Context, *ent.BiodataMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BiodataFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.BiodataMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BiodataMutation", m)
	}
	return f(ctx, mv)
}

// The EducationFunc type is an adapter to allow the use of ordinary
// function as Education mutator.
type EducationFunc func(context.Context, *ent.EducationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EducationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.EducationMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EducationMutation", m)
	}
	return f(ctx, mv)
}

// The FamilyFunc type is an adapter to allow the use of ordinary
// function as Family mutator.
type FamilyFunc func(context.Context, *ent.FamilyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FamilyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.FamilyMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FamilyMutation", m)
	}
	return f(ctx, mv)
}

// The LanguageFunc type is an adapter to allow the use of ordinary
// function as Language mutator.
type LanguageFunc func(context.Context, *ent.LanguageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LanguageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.LanguageMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LanguageMutation", m)
	}
	return f(ctx, mv)
}

// The NetworthFunc type is an adapter to allow the use of ordinary
// function as Networth mutator.
type NetworthFunc func(context.Context, *ent.NetworthMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NetworthFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.NetworthMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NetworthMutation", m)
	}
	return f(ctx, mv)
}

// The OrganizationFunc type is an adapter to allow the use of ordinary
// function as Organization mutator.
type OrganizationFunc func(context.Context, *ent.OrganizationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OrganizationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.OrganizationMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OrganizationMutation", m)
	}
	return f(ctx, mv)
}

// The RegisterFunc type is an adapter to allow the use of ordinary
// function as Register mutator.
type RegisterFunc func(context.Context, *ent.RegisterMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RegisterFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.RegisterMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RegisterMutation", m)
	}
	return f(ctx, mv)
}

// The ScholarshipFunc type is an adapter to allow the use of ordinary
// function as Scholarship mutator.
type ScholarshipFunc func(context.Context, *ent.ScholarshipMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ScholarshipFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.ScholarshipMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ScholarshipMutation", m)
	}
	return f(ctx, mv)
}

// The SocialMediaFunc type is an adapter to allow the use of ordinary
// function as SocialMedia mutator.
type SocialMediaFunc func(context.Context, *ent.SocialMediaMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SocialMediaFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.SocialMediaMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SocialMediaMutation", m)
	}
	return f(ctx, mv)
}

// The TalentFunc type is an adapter to allow the use of ordinary
// function as Talent mutator.
type TalentFunc func(context.Context, *ent.TalentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TalentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TalentMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TalentMutation", m)
	}
	return f(ctx, mv)
}

// The TrainingFunc type is an adapter to allow the use of ordinary
// function as Training mutator.
type TrainingFunc func(context.Context, *ent.TrainingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TrainingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TrainingMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TrainingMutation", m)
	}
	return f(ctx, mv)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.UserMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
	}
	return f(ctx, mv)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
//
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
//
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
//
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
//
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
