// Code generated by entc, DO NOT EDIT.

package socialmedia

const (
	// Label holds the string label denoting the socialmedia type in the database.
	Label = "social_media"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstagram holds the string denoting the instagram field in the database.
	FieldInstagram = "instagram"
	// FieldFacebook holds the string denoting the facebook field in the database.
	FieldFacebook = "facebook"
	// FieldTiktok holds the string denoting the tiktok field in the database.
	FieldTiktok = "tiktok"
	// FieldTwitter holds the string denoting the twitter field in the database.
	FieldTwitter = "twitter"
	// EdgeRegister holds the string denoting the register edge name in mutations.
	EdgeRegister = "register"
	// Table holds the table name of the socialmedia in the database.
	Table = "social_media"
	// RegisterTable is the table that holds the register relation/edge. The primary key declared below.
	RegisterTable = "social_media_register"
	// RegisterInverseTable is the table name for the Register entity.
	// It exists in this package in order to avoid circular dependency with the "register" package.
	RegisterInverseTable = "registers"
)

// Columns holds all SQL columns for socialmedia fields.
var Columns = []string{
	FieldID,
	FieldInstagram,
	FieldFacebook,
	FieldTiktok,
	FieldTwitter,
}

var (
	// RegisterPrimaryKey and RegisterColumn2 are the table columns denoting the
	// primary key for the register relation (M2M).
	RegisterPrimaryKey = []string{"social_media_id", "register_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
