// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Kynesia/ent/biodata"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Biodata is the model entity for the Biodata schema.
type Biodata struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Biodata) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case biodata.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Biodata", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Biodata fields.
func (b *Biodata) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case biodata.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			b.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Biodata.
// Note that you need to call Biodata.Unwrap() before calling this method if this Biodata
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Biodata) Update() *BiodataUpdateOne {
	return (&BiodataClient{config: b.config}).UpdateOne(b)
}

// Unwrap unwraps the Biodata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Biodata) Unwrap() *Biodata {
	tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Biodata is not a transactional entity")
	}
	b.config.driver = tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Biodata) String() string {
	var builder strings.Builder
	builder.WriteString("Biodata(")
	builder.WriteString(fmt.Sprintf("id=%v", b.ID))
	builder.WriteByte(')')
	return builder.String()
}

// BiodataSlice is a parsable slice of Biodata.
type BiodataSlice []*Biodata

func (b BiodataSlice) config(cfg config) {
	for _i := range b {
		b[_i].config = cfg
	}
}
