// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Kynesia/ent/training"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrainingCreate is the builder for creating a Training entity.
type TrainingCreate struct {
	config
	mutation *TrainingMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TrainingCreate) SetName(s string) *TrainingCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tc *TrainingCreate) SetNillableName(s *string) *TrainingCreate {
	if s != nil {
		tc.SetName(*s)
	}
	return tc
}

// SetPeriod sets the "period" field.
func (tc *TrainingCreate) SetPeriod(s string) *TrainingCreate {
	tc.mutation.SetPeriod(s)
	return tc
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (tc *TrainingCreate) SetNillablePeriod(s *string) *TrainingCreate {
	if s != nil {
		tc.SetPeriod(*s)
	}
	return tc
}

// SetYear sets the "year" field.
func (tc *TrainingCreate) SetYear(s string) *TrainingCreate {
	tc.mutation.SetYear(s)
	return tc
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (tc *TrainingCreate) SetNillableYear(s *string) *TrainingCreate {
	if s != nil {
		tc.SetYear(*s)
	}
	return tc
}

// SetOrganizer sets the "organizer" field.
func (tc *TrainingCreate) SetOrganizer(s string) *TrainingCreate {
	tc.mutation.SetOrganizer(s)
	return tc
}

// SetNillableOrganizer sets the "organizer" field if the given value is not nil.
func (tc *TrainingCreate) SetNillableOrganizer(s *string) *TrainingCreate {
	if s != nil {
		tc.SetOrganizer(*s)
	}
	return tc
}

// SetCertificate sets the "certificate" field.
func (tc *TrainingCreate) SetCertificate(s string) *TrainingCreate {
	tc.mutation.SetCertificate(s)
	return tc
}

// SetNillableCertificate sets the "certificate" field if the given value is not nil.
func (tc *TrainingCreate) SetNillableCertificate(s *string) *TrainingCreate {
	if s != nil {
		tc.SetCertificate(*s)
	}
	return tc
}

// Mutation returns the TrainingMutation object of the builder.
func (tc *TrainingCreate) Mutation() *TrainingMutation {
	return tc.mutation
}

// Save creates the Training in the database.
func (tc *TrainingCreate) Save(ctx context.Context) (*Training, error) {
	var (
		err  error
		node *Training
	)
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TrainingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TrainingCreate) SaveX(ctx context.Context) *Training {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TrainingCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TrainingCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TrainingCreate) check() error {
	return nil
}

func (tc *TrainingCreate) sqlSave(ctx context.Context) (*Training, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *TrainingCreate) createSpec() (*Training, *sqlgraph.CreateSpec) {
	var (
		_node = &Training{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: training.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: training.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: training.FieldName,
		})
		_node.Name = &value
	}
	if value, ok := tc.mutation.Period(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: training.FieldPeriod,
		})
		_node.Period = &value
	}
	if value, ok := tc.mutation.Year(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: training.FieldYear,
		})
		_node.Year = &value
	}
	if value, ok := tc.mutation.Organizer(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: training.FieldOrganizer,
		})
		_node.Organizer = &value
	}
	if value, ok := tc.mutation.Certificate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: training.FieldCertificate,
		})
		_node.Certificate = &value
	}
	return _node, _spec
}

// TrainingCreateBulk is the builder for creating many Training entities in bulk.
type TrainingCreateBulk struct {
	config
	builders []*TrainingCreate
}

// Save creates the Training entities in the database.
func (tcb *TrainingCreateBulk) Save(ctx context.Context) ([]*Training, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Training, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrainingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TrainingCreateBulk) SaveX(ctx context.Context) []*Training {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TrainingCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TrainingCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
