// Code generated by entc, DO NOT EDIT.

package achievement

const (
	// Label holds the string label denoting the achievement type in the database.
	Label = "achievement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldOrganizer holds the string denoting the organizer field in the database.
	FieldOrganizer = "organizer"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// Table holds the table name of the achievement in the database.
	Table = "achievements"
)

// Columns holds all SQL columns for achievement fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldOrganizer,
	FieldLevel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
