// Code generated by entc, DO NOT EDIT.

package register

const (
	// Label holds the string label denoting the register type in the database.
	Label = "register"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatusOne holds the string denoting the statusone field in the database.
	FieldStatusOne = "status_one"
	// FieldStatusTwo holds the string denoting the statustwo field in the database.
	FieldStatusTwo = "status_two"
	// FieldOnlineInterview holds the string denoting the onlineinterview field in the database.
	FieldOnlineInterview = "online_interview"
	// FieldInterviewTime holds the string denoting the interviewtime field in the database.
	FieldInterviewTime = "interview_time"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeScholarship holds the string denoting the scholarship edge name in mutations.
	EdgeScholarship = "scholarship"
	// Table holds the table name of the register in the database.
	Table = "registers"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "registers"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_registers"
	// ScholarshipTable is the table that holds the scholarship relation/edge.
	ScholarshipTable = "registers"
	// ScholarshipInverseTable is the table name for the Scholarship entity.
	// It exists in this package in order to avoid circular dependency with the "scholarship" package.
	ScholarshipInverseTable = "scholarships"
	// ScholarshipColumn is the table column denoting the scholarship relation/edge.
	ScholarshipColumn = "scholarship_registers"
)

// Columns holds all SQL columns for register fields.
var Columns = []string{
	FieldID,
	FieldStatusOne,
	FieldStatusTwo,
	FieldOnlineInterview,
	FieldInterviewTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "registers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"scholarship_registers",
	"user_registers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatusTwo holds the default value on creation for the "statusTwo" field.
	DefaultStatusTwo int
)
