// Code generated by entc, DO NOT EDIT.

package training

const (
	// Label holds the string label denoting the training type in the database.
	Label = "training"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldOrganizer holds the string denoting the organizer field in the database.
	FieldOrganizer = "organizer"
	// FieldCertificate holds the string denoting the certificate field in the database.
	FieldCertificate = "certificate"
	// Table holds the table name of the training in the database.
	Table = "trainings"
)

// Columns holds all SQL columns for training fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPeriod,
	FieldYear,
	FieldOrganizer,
	FieldCertificate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
